/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ddb0f9e7-bb1d-4b13-8924-e8de72005d58",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CZivUcOLx",
    "aws_user_pools_web_client_id": "5g3duimrp6nnsndolovk0it7ck",
    "oauth": {}
};


export default awsmobile;
